name: Build and Release Firmware

on:
  push:
    tags:
      - '*'

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install build tools
      run: |
        choco install make mingw gcc-arm-embedded -y

    - name: Add build tools to PATH
      run: |
        echo "C:\ProgramData\chocolatey\lib\mingw\tool" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        echo "C:\ProgramData\Chocolatey\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Show installed build tools
      run: |
        get-command mingw32-make.exe
        get-command gcc.exe
        get-command arm-none-eabi-gcc.exe

    - name: Download Atmel SAMD20 DFP
      run: |
        Invoke-WebRequest -Uri "http://packs.download.atmel.com/Atmel.SAMD20_DFP.1.3.165.atpack" -OutFile "Atmel.SAMD20_DFP.atpack"

    - name: Extract Atmel SAMD20 DFP
      run: |
        Expand-Archive -Path "Atmel.SAMD20_DFP.atpack" -DestinationPath "SAMD20_DFP"

    - name: Download CMSIS 5.4.0
      run: |
        Invoke-WebRequest -Uri "https://github.com/ARM-software/CMSIS_5/archive/refs/tags/5.4.0.zip" -OutFile "CMSIS_5.4.0.zip"

    - name: Extract CMSIS 5.4.0
      run: |
        Expand-Archive -Path "CMSIS_5.4.0.zip" -DestinationPath "CMSIS_5.4.0"

    #- name: Print SAMD20 DFP
    #  run : |
    #    get-childitem .\CMSIS_5.4.0\ -recurse
    #    get-childitem .\SAMD20_DFP\ -recurse

    - name: Update Makefile paths
      run: |
        python utilities\scripts\update_makefile.py
        python utilities\scripts\make_dep_dirs.py

    - name: Build project
      run: |
        cd implementations\samd20-optiboot-custom\samd20-optiboot-custom\Debug
        make all

    - name: Create release artifact
      #if: startsWith(github.ref, 'refs/tags/v')
      run: |
        mkdir -p release\bin
        mkdir -p release\bootloader_assets
        mkdir -p release\bootloader_assets\user
        mkdir -p release\bootloader_assets\deps\embedded-external-flash-memory
        mkdir -p release\hex_writer_assets\app
        mkdir -p release\hex_writer_assets\user
        cp implementations\samd20-optiboot-custom\samd20-optiboot-custom\Debug\samd20-optiboot-custom.* release\bin
        cp src\*.c release\bootloader_assets
        cp src\*.h release\bootloader_assets
        cp src\user\* release\bootloader_assets\user
        cp src\deps\embedded-external-flash-memory\* release\bootloader_assets\deps\embedded-external-flash-memory
        cp src\app\* release\hex_writer_assets\app
        cp src\user\user_settings.h release\hex_writer_assets\user
        $version = .\utilities\version\get_version.ps1
        tar -czvf "release.tar.gz" release

    - name: Upload release artifact
      # if: startsWith(github.ref, 'refs/tags/*')
      uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: release/

    - name: Create GitHub Release
      # if: startsWith(github.ref, 'refs/tags/*')
      uses: softprops/action-gh-release@v1
      with:
        files: release.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
